### PR TITLE
Web accessiblity report

### PR DESCRIPTION
**Pull request by zainsadaqat**
# Web Accessibility Report

> Listing all points that I have to check, i.e: 

* Page titles - **no issues found**
* Image text alternatives (alt text) - **no issues found**
* Text headings - **no issues found**
* Color contrast - **no issues found**
* Resize - **no issues found**
* Interaction - **no issues found**
* Moving content - **no issues found**
* Multimedia - **no issues found**
* The basic structure of the page - **no issues found**

### CODE REVIEW

**Comment by ahmetbozaci** [comment]
# STATUS: Changes Required  ♻️ 

## Hello @✋🏼  Your project is great. You are almost done. However there are some issues you should fix. Please fix them then your project will be approved.


### ♻️ Request changes ♻️
 
- [ ] You should update title. Please check this [article](https://www.w3.org/WAI/test-evaluate/preliminary/#title) again.

- [ ] You should update image alternative text. Please check this article (https://www.w3.org/WAI/test-evaluate/preliminary/#images) again. 

- [ ] You  use h1 tag in about myself text. You should use h1 tag in this text

_**Check the comment about that  under the review.**_


### Cheers and Happy coding! 💻 👏
cat on laptop



___
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._

**Review by ahmetbozaci — CHANGES_REQUESTED** [review]
# STATUS: Changes Required  ♻️ 

## Hello @zainsadaqat ✋🏼  Your project is great. You are almost done. However there are some issues you should fix. Please fix them then your project will be approved.


### ♻️ Request changes ♻️
 
- [x] You should update title. Please check this [article](https://www.w3.org/WAI/test-evaluate/preliminary/#title) again.

- [x] You should update images alternative text. Please check this [article](https://www.w3.org/WAI/test-evaluate/preliminary/#images) again and  check image alternative text. 

- [x] You  use h1 tag in about myself text. You should use h1 tag  in this part.

image

- [ ] When you are creating form you don't have to use list tags.
image

- [x]  Navbar links currently are leading to nowhere, I suggest that you link them to the related section. Also you should check other links in page

image







### Cheers and Happy coding! 💻 👏
cat on laptop


___
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
## STATUS: Changes Requested :recycle:

Hi @zainsadaqat

Good job so far!:clap::clap:
You have done well in implementing the changes requested by the previous reviewer :clap:, However, there are some issues that you still need to work on to go to the next project but you are almost there!:muscle:

##  Required Changes:writing_hand:
- [x] Please double check the color contrast of the project. Use this [link](https://www.aditus.io/button-contrast-checker/) to check for the color contrast and fix it. 

- [x] Some of the colors you've chosen for your portfolio currently don't meet WebAIM accessibility standards for contrast ratio. Please readjust your color palette by using a color contrast validator tool like this [one](https://color.a11y.com/%5C)  to access contrast ratio.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Review by Shaher-11 — APPROVED** [review]
#### Hello @zainsadaqat,

# Congratulations! 🎉 
#### Your project is approved!  There is nothing else to say other than... it's time to merge it :muscle: :muscle::muscle:

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

**Comment by zainsadaqat** [comment]
# Thanks, @Shaher-11 for approving this pull request!

**Pull request merged**
